

export const metadata = {
  title: "services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <>
        <header></header>
        {children}
        <footer></footer>
        </>
  );
}
