
// export const metadata = {
//   title: {
//     template: "%s | blogs", 
//     default: "blogs"
//   },
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
      <>
        <header></header>
        {children}
        <footer></footer>
        </>
  );
}
